#use_frameworks!
#source 'https://github.com/CocoaPods/Specs.git'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
source 'https://github.com/wenchao8023/CwenSpec.git'
source 'https://github.com/ModulizationDemo/PrivatePods.git'

platform :ios, '9.0'

target 'BookShop_Example' do
  pod 'BookShop', :path => '../'
end

#target 'BSell' do
#  pod 'BookShop', :path => '../'
#end
