#use_frameworks!
source 'https://github.com/wenchao8023/CwenSpec.git'

platform :ios, '9.0'

target 'BookShop_Example' do
  pod 'BookShop', :path => '../'
  pod 'ManagerBook', '~>0.1.0'
  

  target 'BookShop_Tests' do
    inherit! :search_paths

    
  end
end
